title: Ben Huston's Portfolio
#logo: /Images/linkedpic.jpg
description: Currently working as a Power BI Data Analyst for Procentrix. Some of my hard skills include SQL, Python, R, visualization tools (Power BI, Tableau), and Excel.
In December of 2021 I completed my B.S. degree in Mathematics with a minor in Computer Science a semester early at the University of Vermont. I completed this degree with a 3.96 GPA, being named to the Dean’s list six of the seven semesters. In December 2022 I was one of two students in my class who completed the Accelerated Masters program in Mathematics at UVM.
theme: jekyll-theme-Slate
