title: Ben Huston's Data Portfolio
#logo: /Images/linkedpic.jpg
description: Currently working as a Data Analyst for Procentrix LLC. Some of my hard skills include SQL, Python, R, visualization tools (Power BI, Tableau), and Excel.<a href="https://www.linkedin.com/in/benhustondataanalyst/">Linkedin Account</a>
theme: jekyll-theme-Slate
