title: Ben Huston's Portfolio
#logo: /Images/linkedpic.jpg
description: Currently working as a Power BI Data Analyst for Procentrix. Some of my hard skills include SQL, Python, R, visualization tools (Power BI, Tableau), and Excel.
theme: jekyll-theme-Slate
