title: Ben Huston's Data Portfolio
#logo: /Images/linkedpic.jpg
description: "deleteCurrently working as a Data Analyst for Procentrix LLC. Some of my hard skills include: SQL, Python, R, visualization tools (Power BI, Tableau), and Excel."
theme: jekyll-theme-Slate
